# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sP3oM5gZ_nL1Zs5BpUyUD1JD3gUc1JM
"""

import pandas as pd
import numpy as np

# Set seed for reproducible results
np.random.seed(101)

# 1. CREATE SPRINT TASK LOGS DATASET
n_tasks = 25

task_names = [
    'User Auth API', 'Landing Page UI', 'Database Migration', 'Payment Gateway Integration',
    'Dashboard Charts', 'Bug Fix: Search Bar', 'Profile Page Redesign', 'Email Notifications',
    'CI/CD Pipeline Setup', 'Settings API', 'Dark Mode Toggle', 'Data Export Feature',
    'Unit Tests: Auth', 'Performance Optimization', 'Analytics Tracking', 'SEO Meta Tags',
    'Role-Based Access', 'CSV Import Feature', 'Localization Setup', 'Session Timeout Fix',
    '3rd Party Webhook', 'Image Upload Compression', 'Footer Links Cleanup', 'SSL Setup', 'Audit Log Service'
]

assignees = ['Alex', 'Priya', 'Rohan', 'Sara', 'David']
statuses = ['Completed', 'Completed', 'Completed', 'Blocked', 'In Progress']
sprints = ['Sprint 1', 'Sprint 2']

data = {
    'Task_ID': [f'TSK-{100 + i}' for i in range(n_tasks)],
    'Task_Name': task_names[:n_tasks],
    'Sprint': np.random.choice(sprints, size=n_tasks, p=[0.5, 0.5]),
    'Assignee': np.random.choice(assignees, size=n_tasks),
    'Status': np.random.choice(['Completed', 'Blocked', 'In Progress'], size=n_tasks, p=[0.68, 0.20, 0.12]),
    'Estimated_Hours': np.random.randint(4, 16, size=n_tasks),
}

df = pd.DataFrame(data)

# Generate actual hours based on status (Blocked tasks take much longer)
actual_hours = []
for idx, row in df.iterrows():
    if row['Status'] == 'Blocked':
        actual_hours.append(row['Estimated_Hours'] + np.random.randint(6, 12))
    elif row['Status'] == 'Completed':
        actual_hours.append(row['Estimated_Hours'] + np.random.randint(-2, 4))
    else:
        actual_hours.append(row['Estimated_Hours'] + np.random.randint(1, 5))

df['Actual_Hours'] = actual_hours

# 2. CALCULATE PM & ANALYTICS METRICS
# Formula: Variance = Actual - Estimated (Positive means delayed)
df['Hour_Variance'] = df['Actual_Hours'] - df['Estimated_Hours']
df['Is_Delayed'] = df['Hour_Variance'].apply(lambda x: 1 if x > 0 else 0)

print("=== 1. SPRINT DATASET SAMPLE ===")
print(df.head(10), "\n")

# Aggregate Summary Metrics
sprint_summary = df.groupby('Sprint').agg(
    Total_Tasks=('Task_ID', 'count'),
    Total_Est_Hours=('Estimated_Hours', 'sum'),
    Total_Act_Hours=('Actual_Hours', 'sum'),
    Blocked_Tasks=('Status', lambda x: (x == 'Blocked').sum()),
    Avg_Delay_Hours=('Hour_Variance', 'mean')
).reset_index()

sprint_summary['Estimation_Accuracy_%'] = round(
    (sprint_summary['Total_Est_Hours'] / sprint_summary['Total_Act_Hours']) * 100, 2
)

print("=== 2. SPRINT PERFORMANCE SUMMARY ===")
print(sprint_summary, "\n")

# Save dataset to CSV for Spreadsheet / Portfolio upload
df.to_csv("sprint_delivery_tracker.csv", index=False)
print("Saved dataset to 'sprint_delivery_tracker.csv' successfully!")

from google.colab import files

# Triggers the download prompt in your browser
files.download("sprint_delivery_tracker.csv")